### ISSUE TITLE
Site design broken

### ISSUE THREAD

**Issue by Andre601** [botblock/botblock.github.io#2]
The new design doesn't seem to work that very well.
Using Google Chrome 79.0.3945.88 (official build) (64-bit)

![image](https://user-images.githubusercontent.com/11576465/71782550-8b526e80-2fdb-11ea-85d9-e0c72243a492.png)

**Comment by MattIPv4** [comment]
Oops, didn't know this used prod styling.
Needs to use the new sidebar & main layout from prod.

**Comment by Andre601** [comment]
This is fixed by now... Surprised it wasn't close yet.
